[workspace]
members = ["rust"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Paul Milesi <paul.milesi@example.com>"]
license = "MIT"
repository = "https://github.com/paulmilesi/pytest-diff"
