[workspace]
members = ["rust"]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2021"
authors = ["Paul Milesi"]
license = "MIT"
repository = "https://github.com/PaulM5406/pytest-difftest"
